title = "Tavish Armstrong"
languageCode = "en-us"
baseurl = "http://tavisharmstrong.com/"
theme = "super-minimal"
pygmentsstyle = "colorful"
PygmentsCodeFences = true
[permalinks]
    post = "/:year/:month/:day/:slug"
